runner:
  device: cpu
  epoch: 1000
  warmup: 100
  dry_run: True

optimizer:
  init_lr: 1e-5
  weight_decay: 5e-4
  adam_eps: 5e-9
  clip: 1

scheduler:
  factor: 0.9
  patience: 10

dataset:
  name: Multi30k
  path: .data/datasets/Multi30k
  batch_size: 32

model:
  name: transformer
  max_len: 256
  d_model: 512
  num_layers: 6
  num_head: 8
  ffn_hidden: 2048
  drop_prob: 0.1

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}